import ProjectImg from "./assets/mproject.png";
import ProjectImg2 from "./assets/upable.png";
import ProjectImg3 from "./assets/skorboard.png";
import ProjectImg4 from "./assets/clear slate.png";
import ProjectImg5 from "./assets/no cloud.png";
import ProjectImg6 from "./assets/swing sauce.png";
import ResearchImg from './assets/research.jpg'
import TravelImg from "./assets/travel.jpg";
import {generateSlug} from './utils/slugify'

const projectDetails = [
  {
    title: "Break and Bread",
    role: "Full Stack Developer",
    description: [
      "Break and Bread is a website offering AIdriven meal planning, personalized recipes, and nutrition details to simplify healthy eating.",
    ],
    features: [
      "Partnered with HandCraftedNotes, a forward-thinking startup focused on transforming client engagement for businesses.",
      "Served as the Lead Engineer, taking responsibility for the overarching system architecture and technical strategy.",
      "Designed and developed advanced automated machines tailored to streamline and enhance operational processes.",
      "Created robust, scalable, and efficient system frameworks to support innovative business solutions.",
    ],
    skill: "ReactJS, NodeJS, Firebase, MUI, Generative AI",
    image: ProjectImg,
    link: "https://www.breakbread.ai/",
    clientName: "Temford",
    type: "Website",
    duration: "1 Month",
    slug: generateSlug("Break and Bread"),
  },
  {
    title: "Upable",
    role: "Full Stack Developer",
    description: [
      "Upable helps users gain traction, feedback, and financial support for their ideas while enabling easy sharing to broaden their reach.",
    ],
    features: [
      "Partnered with HandCraftedNotes, a forward-thinking startup focused on transforming client engagement for businesses.",
      "Served as the Lead Engineer, taking responsibility for the overarching system architecture and technical strategy.",
      "Designed and developed advanced automated machines tailored to streamline and enhance operational processes.",
      "Created robust, scalable, and efficient system frameworks to support innovative business solutions.",
    ],
    skill: "ReactJS, NodeJS, Firebase, MUI",
    image: ProjectImg2,
    link: "https://upable.org",
    clientName: "Temford",
    type: "Website",
    duration: "1 Month",
    slug: generateSlug("Upable"),
  },
  {
    title: "Skorboard",
    role: "Full Stack Developer",
    description: [
      "SKORBOARD enhances game nights by streaming live sports with real-time updates and extensive coverage, bringing the excitement directly to your space.",
    ],
    features: [
      "Partnered with HandCraftedNotes, a forward-thinking startup focused on transforming client engagement for businesses.",
      "Served as the Lead Engineer, taking responsibility for the overarching system architecture and technical strategy.",
      "Designed and developed advanced automated machines tailored to streamline and enhance operational processes.",
      "Created robust, scalable, and efficient system frameworks to support innovative business solutions.",
    ],
    skill: "ReactJS, NodeJS, Firebase, MUI",
    image: ProjectImg3,
    link: "https://www.fantronics.com",
    clientName: "Temford",
    type: "Website",
    duration: "1 Month",
    slug: generateSlug("Skorboard"),
  },

  {
    title: "Clear Slate",
    role: "Full Stack Developer",
    description: [
      "ClearSlate helps you verify whether an image has been marked as AI-generated by checking for metadata tags that are commonly added by AI image generators, like DALL-E.",
    ],
    features: [
      "Partnered with HandCraftedNotes, a forward-thinking startup focused on transforming client engagement for businesses.",
      "Served as the Lead Engineer, taking responsibility for the overarching system architecture and technical strategy.",
      "Designed and developed advanced automated machines tailored to streamline and enhance operational processes.",
      "Created robust, scalable, and efficient system frameworks to support innovative business solutions.",
    ],
    skill: "Python, OpenCv, Machine learning, ffmpeg, Drone Development ",
    image: ProjectImg4,
    link: "https://clearslate.io/",
    clientName: "Temford",
    type: "Website",
    duration: "1 Month",
    slug: generateSlug("Clear Slate"),
  },
];


export { projectDetails };
